---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: capvcd-medium-cluster
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: capvcdclusters
      sourceRef:
        kind: HelmRepository
        name: dkp-capi-clusters
        namespace: kommander-flux
      version: 0.4.0 
  interval: 2m  
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  valuesFrom:
    - kind: ConfigMap
      name: capvcd-medium-1.24.6-d2iq-defaults
  targetNamespace: customer